<div class="wrapper cleafix">
	<!-- vtex:contentPlaceHolder id="bannerDiferenciais" /-->
	<?php include("subtemplates/banners-diferenciais.php") ?>
	<!-- end vtex:contentPlaceHolder id="bannerDiferenciais" /-->

	<!-- container-bloco-central -->
	<div class="container-bloco-central clearfix">
		<div class="coluna-super-banner">
			<div id="bannerSuperDestaque" class="banner-super-destaque">
				<div class="box-banner inicial"><img src="./arquivos/banner-super-destaque-home.jpg" alt="" /></div>
				<div class="box-banner"><img src="./arquivos/banner-super-destaque-home2.jpg" alt="" /></div>
				<div class="box-banner"><img src="./arquivos/banner-super-destaque-home3.jpg" alt="" /></div>
			</div><!-- end bannerSuperDestaque -->

			<div id="paginacaoBanner" class="pager-banner-central clearfix"></div>
		</div><!-- end coluna-super-banner -->

		<div class="coluna-banners">
			<div class="banner-superior-direito">
				<img src="./arquivos/banner-superior-direito.png" alt="" />
			</div>

			<div class="container-newsletter-home">
				<h5>*Cadastre agora seu e-mail e receba nossas ofertas com até 70% de desconto em tênis, roupas e acessórios</h5>
				<!-- <vtex.cmc:newsletterOptIn/> -->
				<div class="newsletter">
					<h3 class="newsletter-title">Assine nossa newsletter</h3>
					<fieldset>
						<p>Receba nossos e-mails repletos de dicas e novidades da Netmall:</p>
						<input id="newsletterClientName" onfocus="newsSelect(this,'Digite seu nome...');" onblur="newsLeave(this,'Digite seu nome...');" class="newsletter-client-name" value="Digite seu nome..." size="20" type="text" name="newsClientName">
						<input id="newsletterClientEmail" onfocus="newsSelect(this,'Digite seu e-mail...');" onblur="newsLeave(this,'Digite seu e-mail...');" class="newsletter-client-email" value="Digite seu e-mail..." size="20" type="text" name="newsletterClientEmail">
						<input id="newsletterButtonOK" class="btn-ok newsletter-button-ok" value="ok" type="button" name="newsletterButtonOK">
						<input id="newsletterLoading" type="hidden" class="newsletter-loading" value="Processando...">
						<input id="newsletterSuccess" type="hidden" class="newsletter-success" value="Obrigado por se cadastrar na NetMall!">
						<input id="newsletterSuccess2" type="hidden" class="newsletter-success2" value="Em breve estaremos entrando em contato com você para oferecer as melhores promoções.">
						<input id="newsletterError" type="hidden" class="newsletter-error" value="Encontramos um erro no cadastro de suas informações.&lt;br /&gt;Por favor, tente novamente!">
						<input id="newsInternalPage" type="hidden" value="_">
						<input id="newsInternalPart" type="hidden" value="newsletter">
						<input id="newsInternalCampaign" type="hidden" value="newsletter:opt-in">
					</fieldset>
					<span class="rt"></span><span class="rb"></span><span class="lb"></span><span class="lt"></span>
				</div>
				<!-- end <vtex.cmc:newsletterOptIn/> -->
			</div><!-- container-newsletter-home -->

			<div class="banner-inferior-direito">
				<img src="./arquivos/banner-inferior-direito.png" alt="" />
			</div>
		</div><!-- end coluna-banners -->
	</div><!-- end container-bloco-central -->

	<div id="carrossel1" class="container-carrossel clearfix">
		<h2>Lançamentos</h2>
		<ul>
			<li><div class="imgProduto"><img src="./arquivos/fake-carrossel.jpg" width="292" height="292" alt="imagem-1"></div><div class="containerDescProd"><div class="prodName"><a href="http://develop-netmall.vtexcommerce.com.br/Vestido_tomara_que_caia/p">Vestido Tomara Que Caia</a></div><div class="prodDesc"><p class="texto brand aishty">aishty</p></div><div class="prodPrice"><span class="valueProd">R$ 39,90</span> ou <span class="quantidade-parcela">3x</span> de <span class="valor-parcela">R$ 13,30</span></div></div><div class="container-espiar"><a class="thickbox" alt="Vestido Tomara Que Caia" href="http://develop-netmall.vtexcommerce.com.br/quick-view/?idproduto=2000005?KeepThis=true&amp;TB_iframe=true">Espiar</a></div><p></p></li>
			<li><div class="imgProduto"><img src="./arquivos/fake-carrossel.jpg" width="292" height="292" alt="imagem-1"></div><div class="containerDescProd"><div class="prodName"><a href="http://develop-netmall.vtexcommerce.com.br/Vestido_tomara_que_caia/p">Vestido Tomara Que Caia</a></div><div class="prodDesc"><p class="texto brand aishty">aishty</p></div><div class="prodPrice"><span class="valueProd">R$ 39,90</span> ou <span class="quantidade-parcela">3x</span> de <span class="valor-parcela">R$ 13,30</span></div></div><div class="container-espiar"><a class="thickbox" alt="Vestido Tomara Que Caia" href="http://develop-netmall.vtexcommerce.com.br/quick-view/?idproduto=2000005?KeepThis=true&amp;TB_iframe=true">Espiar</a></div><p></p></li>
			<li><div class="imgProduto"><img src="./arquivos/fake-carrossel.jpg" width="292" height="292" alt="imagem-1"></div><div class="containerDescProd"><div class="prodName"><a href="http://develop-netmall.vtexcommerce.com.br/Vestido_tomara_que_caia/p">Vestido Tomara Que Caia</a></div><div class="prodDesc"><p class="texto brand aishty">aishty</p></div><div class="prodPrice"><span class="valueProd">R$ 39,90</span> ou <span class="quantidade-parcela">3x</span> de <span class="valor-parcela">R$ 13,30</span></div></div><div class="container-espiar"><a class="thickbox" alt="Vestido Tomara Que Caia" href="http://develop-netmall.vtexcommerce.com.br/quick-view/?idproduto=2000005?KeepThis=true&amp;TB_iframe=true">Espiar</a></div><p></p></li>
			<li><div class="imgProduto"><img src="./arquivos/fake-carrossel.jpg" width="292" height="292" alt="imagem-1"></div><div class="containerDescProd"><div class="prodName"><a href="http://develop-netmall.vtexcommerce.com.br/Vestido_tomara_que_caia/p">Vestido Tomara Que Caia</a></div><div class="prodDesc"><p class="texto brand aishty">aishty</p></div><div class="prodPrice"><span class="valueProd">R$ 39,90</span> ou <span class="quantidade-parcela">3x</span> de <span class="valor-parcela">R$ 13,30</span></div></div><div class="container-espiar"><a class="thickbox" alt="Vestido Tomara Que Caia" href="http://develop-netmall.vtexcommerce.com.br/quick-view/?idproduto=2000005?KeepThis=true&amp;TB_iframe=true">Espiar</a></div><p></p></li>
			<li><div class="imgProduto"><img src="./arquivos/fake-carrossel.jpg" width="292" height="292" alt="imagem-1"></div><div class="containerDescProd"><div class="prodName"><a href="http://develop-netmall.vtexcommerce.com.br/Vestido_tomara_que_caia/p">Vestido Tomara Que Caia</a></div><div class="prodDesc"><p class="texto brand aishty">aishty</p></div><div class="prodPrice"><span class="valueProd">R$ 39,90</span> ou <span class="quantidade-parcela">3x</span> de <span class="valor-parcela">R$ 13,30</span></div></div><div class="container-espiar"><a class="thickbox" alt="Vestido Tomara Que Caia" href="http://develop-netmall.vtexcommerce.com.br/quick-view/?idproduto=2000005?KeepThis=true&amp;TB_iframe=true">Espiar</a></div><p></p></li>
			<li><div class="imgProduto"><img src="./arquivos/fake-carrossel.jpg" width="292" height="292" alt="imagem-1"></div><div class="containerDescProd"><div class="prodName"><a href="http://develop-netmall.vtexcommerce.com.br/Vestido_tomara_que_caia/p">Vestido Tomara Que Caia</a></div><div class="prodDesc"><p class="texto brand aishty">aishty</p></div><div class="prodPrice"><span class="valueProd">R$ 39,90</span> ou <span class="quantidade-parcela">3x</span> de <span class="valor-parcela">R$ 13,30</span></div></div><div class="container-espiar"><a class="thickbox" alt="Vestido Tomara Que Caia" href="http://develop-netmall.vtexcommerce.com.br/quick-view/?idproduto=2000005?KeepThis=true&amp;TB_iframe=true">Espiar</a></div><p></p></li>
			<li><div class="imgProduto"><img src="./arquivos/fake-carrossel.jpg" width="292" height="292" alt="imagem-1"></div><div class="containerDescProd"><div class="prodName"><a href="http://develop-netmall.vtexcommerce.com.br/Vestido_tomara_que_caia/p">Vestido Tomara Que Caia</a></div><div class="prodDesc"><p class="texto brand aishty">aishty</p></div><div class="prodPrice"><span class="valueProd">R$ 39,90</span> ou <span class="quantidade-parcela">3x</span> de <span class="valor-parcela">R$ 13,30</span></div></div><div class="container-espiar"><a class="thickbox" alt="Vestido Tomara Que Caia" href="http://develop-netmall.vtexcommerce.com.br/quick-view/?idproduto=2000005?KeepThis=true&amp;TB_iframe=true">Espiar</a></div><p></p></li>
			<li><div class="imgProduto"><img src="./arquivos/fake-carrossel.jpg" width="292" height="292" alt="imagem-1"></div><div class="containerDescProd"><div class="prodName"><a href="http://develop-netmall.vtexcommerce.com.br/Vestido_tomara_que_caia/p">Vestido Tomara Que Caia</a></div><div class="prodDesc"><p class="texto brand aishty">aishty</p></div><div class="prodPrice"><span class="valueProd">R$ 39,90</span> ou <span class="quantidade-parcela">3x</span> de <span class="valor-parcela">R$ 13,30</span></div></div><div class="container-espiar"><a class="thickbox" alt="Vestido Tomara Que Caia" href="http://develop-netmall.vtexcommerce.com.br/quick-view/?idproduto=2000005?KeepThis=true&amp;TB_iframe=true">Espiar</a></div><p></p></li>
			<li class="last"><div class="imgProduto"><img src="./arquivos/fake-carrossel.jpg" width="292" height="292" alt="imagem-1"></div><div class="containerDescProd"><div class="prodName"><a href="http://develop-netmall.vtexcommerce.com.br/Vestido_tomara_que_caia/p">Vestido Tomara Que Caia</a></div><div class="prodDesc"><p class="texto brand aishty">aishty</p></div><div class="prodPrice"><span class="valueProd">R$ 39,90</span> ou <span class="quantidade-parcela">3x</span> de <span class="valor-parcela">R$ 13,30</span></div></div><div class="container-espiar"><a class="thickbox" alt="Vestido Tomara Que Caia" href="http://develop-netmall.vtexcommerce.com.br/quick-view/?idproduto=2000005?KeepThis=true&amp;TB_iframe=true">Espiar</a></div><p></p></li>
		</ul>
		<div class="containerControle left"><a href="#" id="btn-carrossel1-prev" class="btnCarouselPrev hidden">anterior</a></div>
		<div class="containerControle right"><a href="#" id="btn-carrossel1-next" class="btnCarouselNext">próximo</a></div>
	</div><!-- container-carrossel -->

	<div id="carrossel2" class="container-carrossel clearfix">
		<h2>Recomendamos para elas</h2>
		<ul>
			<li><div class="imgProduto"><img src="./arquivos/fake-carrossel.jpg" width="292" height="292" alt="imagem-1"></div><div class="containerDescProd"><div class="prodName"><a href="http://develop-netmall.vtexcommerce.com.br/Vestido_tomara_que_caia/p">Vestido Tomara Que Caia</a></div><div class="prodDesc"><p class="texto brand aishty">aishty</p></div><div class="prodPrice"><span class="valueProd">R$ 39,90</span> ou <span class="quantidade-parcela">3x</span> de <span class="valor-parcela">R$ 13,30</span></div></div><div class="container-espiar"><a class="thickbox" alt="Vestido Tomara Que Caia" href="http://develop-netmall.vtexcommerce.com.br/quick-view/?idproduto=2000005?KeepThis=true&amp;TB_iframe=true">Espiar</a></div><p></p></li>
			<li><div class="imgProduto"><img src="./arquivos/fake-carrossel.jpg" width="292" height="292" alt="imagem-1"></div><div class="containerDescProd"><div class="prodName"><a href="http://develop-netmall.vtexcommerce.com.br/Vestido_tomara_que_caia/p">Vestido Tomara Que Caia</a></div><div class="prodDesc"><p class="texto brand aishty">aishty</p></div><div class="prodPrice"><span class="valueProd">R$ 39,90</span> ou <span class="quantidade-parcela">3x</span> de <span class="valor-parcela">R$ 13,30</span></div></div><div class="container-espiar"><a class="thickbox" alt="Vestido Tomara Que Caia" href="http://develop-netmall.vtexcommerce.com.br/quick-view/?idproduto=2000005?KeepThis=true&amp;TB_iframe=true">Espiar</a></div><p></p></li>
			<li><div class="imgProduto"><img src="./arquivos/fake-carrossel.jpg" width="292" height="292" alt="imagem-1"></div><div class="containerDescProd"><div class="prodName"><a href="http://develop-netmall.vtexcommerce.com.br/Vestido_tomara_que_caia/p">Vestido Tomara Que Caia</a></div><div class="prodDesc"><p class="texto brand aishty">aishty</p></div><div class="prodPrice"><span class="valueProd">R$ 39,90</span> ou <span class="quantidade-parcela">3x</span> de <span class="valor-parcela">R$ 13,30</span></div></div><div class="container-espiar"><a class="thickbox" alt="Vestido Tomara Que Caia" href="http://develop-netmall.vtexcommerce.com.br/quick-view/?idproduto=2000005?KeepThis=true&amp;TB_iframe=true">Espiar</a></div><p></p></li>
			<li><div class="imgProduto"><img src="./arquivos/fake-carrossel.jpg" width="292" height="292" alt="imagem-1"></div><div class="containerDescProd"><div class="prodName"><a href="http://develop-netmall.vtexcommerce.com.br/Vestido_tomara_que_caia/p">Vestido Tomara Que Caia</a></div><div class="prodDesc"><p class="texto brand aishty">aishty</p></div><div class="prodPrice"><span class="valueProd">R$ 39,90</span> ou <span class="quantidade-parcela">3x</span> de <span class="valor-parcela">R$ 13,30</span></div></div><div class="container-espiar"><a class="thickbox" alt="Vestido Tomara Que Caia" href="http://develop-netmall.vtexcommerce.com.br/quick-view/?idproduto=2000005?KeepThis=true&amp;TB_iframe=true">Espiar</a></div><p></p></li>
			<li><div class="imgProduto"><img src="./arquivos/fake-carrossel.jpg" width="292" height="292" alt="imagem-1"></div><div class="containerDescProd"><div class="prodName"><a href="http://develop-netmall.vtexcommerce.com.br/Vestido_tomara_que_caia/p">Vestido Tomara Que Caia</a></div><div class="prodDesc"><p class="texto brand aishty">aishty</p></div><div class="prodPrice"><span class="valueProd">R$ 39,90</span> ou <span class="quantidade-parcela">3x</span> de <span class="valor-parcela">R$ 13,30</span></div></div><div class="container-espiar"><a class="thickbox" alt="Vestido Tomara Que Caia" href="http://develop-netmall.vtexcommerce.com.br/quick-view/?idproduto=2000005?KeepThis=true&amp;TB_iframe=true">Espiar</a></div><p></p></li>
			<li><div class="imgProduto"><img src="./arquivos/fake-carrossel.jpg" width="292" height="292" alt="imagem-1"></div><div class="containerDescProd"><div class="prodName"><a href="http://develop-netmall.vtexcommerce.com.br/Vestido_tomara_que_caia/p">Vestido Tomara Que Caia</a></div><div class="prodDesc"><p class="texto brand aishty">aishty</p></div><div class="prodPrice"><span class="valueProd">R$ 39,90</span> ou <span class="quantidade-parcela">3x</span> de <span class="valor-parcela">R$ 13,30</span></div></div><div class="container-espiar"><a class="thickbox" alt="Vestido Tomara Que Caia" href="http://develop-netmall.vtexcommerce.com.br/quick-view/?idproduto=2000005?KeepThis=true&amp;TB_iframe=true">Espiar</a></div><p></p></li>
			<li><div class="imgProduto"><img src="./arquivos/fake-carrossel.jpg" width="292" height="292" alt="imagem-1"></div><div class="containerDescProd"><div class="prodName"><a href="http://develop-netmall.vtexcommerce.com.br/Vestido_tomara_que_caia/p">Vestido Tomara Que Caia</a></div><div class="prodDesc"><p class="texto brand aishty">aishty</p></div><div class="prodPrice"><span class="valueProd">R$ 39,90</span> ou <span class="quantidade-parcela">3x</span> de <span class="valor-parcela">R$ 13,30</span></div></div><div class="container-espiar"><a class="thickbox" alt="Vestido Tomara Que Caia" href="http://develop-netmall.vtexcommerce.com.br/quick-view/?idproduto=2000005?KeepThis=true&amp;TB_iframe=true">Espiar</a></div><p></p></li>
			<li><div class="imgProduto"><img src="./arquivos/fake-carrossel.jpg" width="292" height="292" alt="imagem-1"></div><div class="containerDescProd"><div class="prodName"><a href="http://develop-netmall.vtexcommerce.com.br/Vestido_tomara_que_caia/p">Vestido Tomara Que Caia</a></div><div class="prodDesc"><p class="texto brand aishty">aishty</p></div><div class="prodPrice"><span class="valueProd">R$ 39,90</span> ou <span class="quantidade-parcela">3x</span> de <span class="valor-parcela">R$ 13,30</span></div></div><div class="container-espiar"><a class="thickbox" alt="Vestido Tomara Que Caia" href="http://develop-netmall.vtexcommerce.com.br/quick-view/?idproduto=2000005?KeepThis=true&amp;TB_iframe=true">Espiar</a></div><p></p></li>
			<li class="last"><div class="imgProduto"><img src="./arquivos/fake-carrossel.jpg" width="292" height="292" alt="imagem-1"></div><div class="containerDescProd"><div class="prodName"><a href="http://develop-netmall.vtexcommerce.com.br/Vestido_tomara_que_caia/p">Vestido Tomara Que Caia</a></div><div class="prodDesc"><p class="texto brand aishty">aishty</p></div><div class="prodPrice"><span class="valueProd">R$ 39,90</span> ou <span class="quantidade-parcela">3x</span> de <span class="valor-parcela">R$ 13,30</span></div></div><div class="container-espiar"><a class="thickbox" alt="Vestido Tomara Que Caia" href="http://develop-netmall.vtexcommerce.com.br/quick-view/?idproduto=2000005?KeepThis=true&amp;TB_iframe=true">Espiar</a></div><p></p></li>
		</ul>
		<div class="containerControle left"><a href="#" id="btn-carrossel2-prev" class="btnCarouselPrev hidden">anterior</a></div>
		<div class="containerControle right"><a href="#" id="btn-carrossel2-next" class="btnCarouselNext">próximo</a></div>
	</div><!-- container-carrossel -->

	<div id="carrossel3" class="container-carrossel clearfix">
		<h2>Recomendamos para eles</h2>
		<ul>
			<li><div class="imgProduto"><img src="./arquivos/fake-carrossel.jpg" width="292" height="292" alt="imagem-1"></div><div class="containerDescProd"><div class="prodName"><a href="http://develop-netmall.vtexcommerce.com.br/Vestido_tomara_que_caia/p">Vestido Tomara Que Caia</a></div><div class="prodDesc"><p class="texto brand aishty">aishty</p></div><div class="prodPrice"><span class="valueProd">R$ 39,90</span> ou <span class="quantidade-parcela">3x</span> de <span class="valor-parcela">R$ 13,30</span></div></div><div class="container-espiar"><a class="thickbox" alt="Vestido Tomara Que Caia" href="http://develop-netmall.vtexcommerce.com.br/quick-view/?idproduto=2000005?KeepThis=true&amp;TB_iframe=true">Espiar</a></div><p></p></li>
			<li><div class="imgProduto"><img src="./arquivos/fake-carrossel.jpg" width="292" height="292" alt="imagem-1"></div><div class="containerDescProd"><div class="prodName"><a href="http://develop-netmall.vtexcommerce.com.br/Vestido_tomara_que_caia/p">Vestido Tomara Que Caia</a></div><div class="prodDesc"><p class="texto brand aishty">aishty</p></div><div class="prodPrice"><span class="valueProd">R$ 39,90</span> ou <span class="quantidade-parcela">3x</span> de <span class="valor-parcela">R$ 13,30</span></div></div><div class="container-espiar"><a class="thickbox" alt="Vestido Tomara Que Caia" href="http://develop-netmall.vtexcommerce.com.br/quick-view/?idproduto=2000005?KeepThis=true&amp;TB_iframe=true">Espiar</a></div><p></p></li>
			<li><div class="imgProduto"><img src="./arquivos/fake-carrossel.jpg" width="292" height="292" alt="imagem-1"></div><div class="containerDescProd"><div class="prodName"><a href="http://develop-netmall.vtexcommerce.com.br/Vestido_tomara_que_caia/p">Vestido Tomara Que Caia</a></div><div class="prodDesc"><p class="texto brand aishty">aishty</p></div><div class="prodPrice"><span class="valueProd">R$ 39,90</span> ou <span class="quantidade-parcela">3x</span> de <span class="valor-parcela">R$ 13,30</span></div></div><div class="container-espiar"><a class="thickbox" alt="Vestido Tomara Que Caia" href="http://develop-netmall.vtexcommerce.com.br/quick-view/?idproduto=2000005?KeepThis=true&amp;TB_iframe=true">Espiar</a></div><p></p></li>
			<li><div class="imgProduto"><img src="./arquivos/fake-carrossel.jpg" width="292" height="292" alt="imagem-1"></div><div class="containerDescProd"><div class="prodName"><a href="http://develop-netmall.vtexcommerce.com.br/Vestido_tomara_que_caia/p">Vestido Tomara Que Caia</a></div><div class="prodDesc"><p class="texto brand aishty">aishty</p></div><div class="prodPrice"><span class="valueProd">R$ 39,90</span> ou <span class="quantidade-parcela">3x</span> de <span class="valor-parcela">R$ 13,30</span></div></div><div class="container-espiar"><a class="thickbox" alt="Vestido Tomara Que Caia" href="http://develop-netmall.vtexcommerce.com.br/quick-view/?idproduto=2000005?KeepThis=true&amp;TB_iframe=true">Espiar</a></div><p></p></li>
			<li><div class="imgProduto"><img src="./arquivos/fake-carrossel.jpg" width="292" height="292" alt="imagem-1"></div><div class="containerDescProd"><div class="prodName"><a href="http://develop-netmall.vtexcommerce.com.br/Vestido_tomara_que_caia/p">Vestido Tomara Que Caia</a></div><div class="prodDesc"><p class="texto brand aishty">aishty</p></div><div class="prodPrice"><span class="valueProd">R$ 39,90</span> ou <span class="quantidade-parcela">3x</span> de <span class="valor-parcela">R$ 13,30</span></div></div><div class="container-espiar"><a class="thickbox" alt="Vestido Tomara Que Caia" href="http://develop-netmall.vtexcommerce.com.br/quick-view/?idproduto=2000005?KeepThis=true&amp;TB_iframe=true">Espiar</a></div><p></p></li>
			<li><div class="imgProduto"><img src="./arquivos/fake-carrossel.jpg" width="292" height="292" alt="imagem-1"></div><div class="containerDescProd"><div class="prodName"><a href="http://develop-netmall.vtexcommerce.com.br/Vestido_tomara_que_caia/p">Vestido Tomara Que Caia</a></div><div class="prodDesc"><p class="texto brand aishty">aishty</p></div><div class="prodPrice"><span class="valueProd">R$ 39,90</span> ou <span class="quantidade-parcela">3x</span> de <span class="valor-parcela">R$ 13,30</span></div></div><div class="container-espiar"><a class="thickbox" alt="Vestido Tomara Que Caia" href="http://develop-netmall.vtexcommerce.com.br/quick-view/?idproduto=2000005?KeepThis=true&amp;TB_iframe=true">Espiar</a></div><p></p></li>
			<li><div class="imgProduto"><img src="./arquivos/fake-carrossel.jpg" width="292" height="292" alt="imagem-1"></div><div class="containerDescProd"><div class="prodName"><a href="http://develop-netmall.vtexcommerce.com.br/Vestido_tomara_que_caia/p">Vestido Tomara Que Caia</a></div><div class="prodDesc"><p class="texto brand aishty">aishty</p></div><div class="prodPrice"><span class="valueProd">R$ 39,90</span> ou <span class="quantidade-parcela">3x</span> de <span class="valor-parcela">R$ 13,30</span></div></div><div class="container-espiar"><a class="thickbox" alt="Vestido Tomara Que Caia" href="http://develop-netmall.vtexcommerce.com.br/quick-view/?idproduto=2000005?KeepThis=true&amp;TB_iframe=true">Espiar</a></div><p></p></li>
			<li><div class="imgProduto"><img src="./arquivos/fake-carrossel.jpg" width="292" height="292" alt="imagem-1"></div><div class="containerDescProd"><div class="prodName"><a href="http://develop-netmall.vtexcommerce.com.br/Vestido_tomara_que_caia/p">Vestido Tomara Que Caia</a></div><div class="prodDesc"><p class="texto brand aishty">aishty</p></div><div class="prodPrice"><span class="valueProd">R$ 39,90</span> ou <span class="quantidade-parcela">3x</span> de <span class="valor-parcela">R$ 13,30</span></div></div><div class="container-espiar"><a class="thickbox" alt="Vestido Tomara Que Caia" href="http://develop-netmall.vtexcommerce.com.br/quick-view/?idproduto=2000005?KeepThis=true&amp;TB_iframe=true">Espiar</a></div><p></p></li>
			<li class="last"><div class="imgProduto"><img src="./arquivos/fake-carrossel.jpg" width="292" height="292" alt="imagem-1"></div><div class="containerDescProd"><div class="prodName"><a href="http://develop-netmall.vtexcommerce.com.br/Vestido_tomara_que_caia/p">Vestido Tomara Que Caia</a></div><div class="prodDesc"><p class="texto brand aishty">aishty</p></div><div class="prodPrice"><span class="valueProd">R$ 39,90</span> ou <span class="quantidade-parcela">3x</span> de <span class="valor-parcela">R$ 13,30</span></div></div><div class="container-espiar"><a class="thickbox" alt="Vestido Tomara Que Caia" href="http://develop-netmall.vtexcommerce.com.br/quick-view/?idproduto=2000005?KeepThis=true&amp;TB_iframe=true">Espiar</a></div><p></p></li>
		</ul>
		<div class="containerControle left"><a href="#" id="btn-carrossel3-prev" class="btnCarouselPrev hidden">anterior</a></div>
		<div class="containerControle right"><a href="#" id="btn-carrossel3-next" class="btnCarouselNext">próximo</a></div>
	</div><!-- container-carrossel -->

	<div class="banners-rodape clearfix">
		<ul>
			<li class="banner"><div class="banner-rodape"><a href="#"><img src="./arquivos/banner-rodape1.jpg" alt="" /></a></div></li>
			<li class="banner"><div class="banner-rodape"><a href="#"><img src="./arquivos/banner-rodape2.jpg" alt="" /></a></div></li>
			<li class="banner last"><div class="banner-rodape"><a href="#"><img src="./arquivos/banner-rodape3.jpg" alt="" /></a></div></li>
		</ul>
	</div><!-- end banners-rodape -->
</div><!-- wrapper -->